Todo
ShivanshSinghnnovative/todo pull request #1
Opened 2023-09-21 13:33 UTC by ShivanshSinghnnovative

2023-09-25 08:50 UTC, PiyushInnotech commented on src/components/AddnewProject.vue
> +    <div v-if="errorMessage.lenght != 0 && title.length == 0" class="error">* please enter title</div>
correctspelling

2023-09-25 08:50 UTC, PiyushInnotech commented on src/components/AddnewProject.vue
> +    <div v-if="errorMessage.lenght != 0 && details.length == 0" class="error">* please enter details</div>
same here

2023-09-25 08:51 UTC, PiyushInnotech commented on src/components/AddnewProject.vue
> +    created() {
use onmount

2023-09-25 08:51 UTC, PiyushInnotech commented on src/components/AddnewProject.vue
> +            console.log(this.todos)
remove console

2023-09-25 08:52 UTC, PiyushInnotech commented on src/App.vue
> +    <router-link to="/" :class="[{ header: currentRoute === '/' || currentRoute === '/completed' || currentRoute === '/ongoing' } , 'heading']"><span>Project</span></router-link>
this way is wrong

2023-09-25 08:53 UTC, PiyushInnotech commented on src/App.vue
> +    <router-link to="/addnewproject" :class="[{ header: currentRoute === '/addnewproject' },'heading']">
same here

2023-09-25 08:54 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +<div class="projectBoxs" v-for="titled in filteredTitles" :key="titled.id" :class="getTitleClass(titled)">
name change from filteredtitles to filteredtodo

2023-09-25 08:54 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +    created() {
use mount

2023-09-25 08:55 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        let todoss = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
use better names

2023-09-25 08:56 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        for (let i = 0; i < todoss.length; i++) {
dont use loop

2023-09-25 08:56 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        filteredTitles() {
use watch

2023-09-25 08:58 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        getTitleClass(titled) {
use directly

2023-09-25 08:59 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        getIconClass(titled) {
same here

2023-09-25 09:01 UTC, PiyushInnotech commented on src/components/LandingPage.vue
> +        completedTodo(idforComplete) {
change function name

2023-09-25 12:32 UTC, meanstack9716 requested changes

2023-09-25 12:32 UTC, meanstack9716 commented on src/App.vue
> +<nav class="content">
move this code to a header component @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/App.vue
> +    computed: {
you are not using currentRoute computed anywhere in this App component, then you did you declare it? @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/components/NotFound.vue
> +<h1 class="error"> 404 not found</h1>
view not formatted @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/components/UpdateTodo.vue
> +            updateddetails: '',
move both updatedtitles and updateddetails into a single object and use it from their.
SO it can be like
project: {
title: "",
description: ""
}

2023-09-25 12:32 UTC, meanstack9716 commented on src/components/UpdateTodo.vue
> +<template>
also its not Todo, it should be Project @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/components/UpdateTodo.vue
> +            this.updatedtitles = todos[editIndex].title;
there is a bug, any once can add/update, blank Project details and description. 
By using multiple spaces. @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/components/UpdateTodo.vue
> +            const index = todos.findIndex(todo => todo.id == id);
duplicate code for todos and index @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/AddnewTodos.vue
> +<template>
add and edit project should be done by a single component, not by 2 component @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/AddnewTodos.vue
> +                if(this.errorMessage.length==0){
code not formatted @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +    <nav class="projectPaths">
create a component for this nav too @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +    </div>
improve code

   `<div class="noTodo" v-if="filteredTodo.length === 0 && this.$route.path === '/viewall'">
        <p>ADD TODO </p>
    </div>
    <div class="noTodo" v-if="filteredTodo.length === 0 && this.$route.path === '/completed'">
        <p>NO COMPLETED TODO </p>
    </div>
    <div class="noTodo" v-if="filteredTodo.length === 0 && this.$route.path === '/ongoing'">
        <p>NO ONGOING TODO</p>
    </div>`
    @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +                titles: [],
what are titles? @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +                heading: ''
what is heading @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +    const STORAGE_KEY = 'vue-todo';
move STORAGE_KEY to env file, and use it from here @ShivanshSinghnnovative

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +            deletetitle(title) {
function name should be camelCase @ShivanshSinghnnovative 
also improve your function names

2023-09-25 12:32 UTC, meanstack9716 commented on src/pages/HomePage.vue
> +            showDetails(todoData) {
improve this function code @ShivanshSinghnnovative

2023-09-26 08:28 UTC, meanstack9716 requested changes

2023-09-26 08:28 UTC, meanstack9716 commented on src/App.vue
> +    <headingText></headingText>
it should be only heading, not heading text. More precisely it should be nav-menu or header. @ShivanshSinghnnovative

2023-09-26 08:28 UTC, meanstack9716 commented on src/components/HeaderText.vue
> +    name: 'headingText',
should be Header, also the file name @ShivanshSinghnnovative

2023-09-26 10:32 UTC, merged